# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-29 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_goods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fruit',
            new_name='Users',
        ),
    ]
