# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-06 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20180806_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Users'),
        ),
    ]
